### ISSUE TITLE
Python 3 traitsui/traitsui/qt4/enum_editor.py float index from devision

### ISSUE THREAD

**Issue by ericjmcd** [enthought/traitsui#306]
There is an integer division for the` incr` variable that is now a float in Python3 which causes an exception when trying to index into a list.  I checked the Python3 feature branch and it isn't corrected there (and doesn't have the // division that is shown below for the `rows` variable.

```
        rows    = (n + cols - 1) // cols
        if self.row_major:
            incr = [ 1 ] * cols
        else:
            incr = [ n / cols ] * cols
            rem  = n % cols
            for i in range( cols ):
                incr[i] += (rem > i)
            incr[-1] = -(reduce( lambda x, y: x + y, incr[:-1], 0 ) - 1)
```

**Comment by corranwebster** [comment]
It looks like this is fixed in master (see https://github.com/enthought/traitsui/blob/master/traitsui/qt4/enum_editor.py#L428) by https://github.com/enthought/traitsui/pull/240

**Comment by ericjmcd** [comment]
Sorry, could have been more explicit.  
`incr = [ n / cols ] * cols`
is the line that is still incorrect.
I didn't see the other lounge fixed in the Python 3 feature branch so I'm guessing it needs a pull for that fix.

**Comment by ericjmcd** [comment]
Oops. lounge should have been line. (On my phone and can't edit the comment)

**Comment by corranwebster** [comment]
Right I see: this is the problem https://github.com/enthought/traitsui/blob/master/traitsui/qt4/enum_editor.py#L432

Will re-open this one and close the other issue.

**Comment by corranwebster** [comment]
Hopefully this is now resolved.  Please re-open if you see any issues.

Thanks for the report and the persistence in the face of my failure to understand!
