### ISSUE TITLE
FAIL: traitsui.tests.test_splitter_prefs_restored.test_splitter_prefs_are_restored

### ISSUE THREAD

**Issue by itziakos** [enthought/traitsui#423]
Seen on a Windows 10 machine running using python 3.5.2 and pyqt5

```python
======================================================================
FAIL: traitsui.tests.test_splitter_prefs_restored.test_splitter_prefs_are_restored
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\...\.edm\envs\traitsui-test-3.5-pyqt5\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\...\.edm\envs\traitsui-test-3.5-pyqt5\lib\site-packages\traitsui-5.2.0.dev356-py3.5.egg\traitsui\tests\_tools.py", line 88, in wrapper
    return item(*args, **kwargs)
  File "C:\Users\...\.edm\envs\traitsui-test-3.5-pyqt5\lib\site-packages\traitsui-5.2.0.dev356-py3.5.egg\traitsui\tests\test_splitter_prefs_restored.py", line 136, in test_splitter_prefs_are_restored
    _get_nattr(ui2.get_prefs()))
AssertionError: b'\x0[54 chars]x00\x00\x00\x00\x02M\x01\xff\xff\xff\xff\x00\x[14 chars]\x01' != b'\x0[54 chars]x00\x89\x00\x00\x02"\x01\xff\xff\xff\xff\x00\x[14 chars]\x01'
```

**Comment by corranwebster** [comment]
I am also seeing this regularly on my local machine (MacOS 10.13, both Python 3 and Python 2.7; pyside and pyqt), but not on Travis CI or Appveyor.

**Comment by rahulporuri** [comment]
closing as this seems to have been fixed in https://github.com/enthought/traitsui/pull/1092

**Comment by aaronayres35** [comment]
I am still seeing this regularly locally when I run the test suite:
```
FAIL: test_splitter_prefs_are_restored (traitsui.tests.test_splitter_prefs_restored.TestSplitterPrefsRestored)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aayres/Desktop/traitsui/traitsui/tests/test_splitter_prefs_restored.py", line 148, in test_splitter_prefs_are_restored
    collapsed_splitter_state, _get_nattr(ui2.get_prefs())
AssertionError: b'\x0[52 chars]0\x00\x00\x00\x00\x02A\x01\xff\xff\xff\xff\x00[16 chars]\x01' != b'\x0[52 chars]0\x00l\x00\x00\x02\x16\x01\xff\xff\xff\xff\x00[16 chars]\x01'

----------------------------------------------------------------------
```
but as mentioned it does not occur on CI for some reason

**Comment by rahulporuri** [comment]
reopening - and it looks like this is an osx only issue.

**Comment by itziakos** [comment]
This error is still visible using Python 3.6, traitsui 7.4.2 and PyQt5-5.14.2 (using Qt 5.12.6)
