### ISSUE TITLE
ListStrEditor (and TabularEditor) does not refresh if Button object adds new row

### ISSUE THREAD

**Issue by flongford** [enthought/traitsui#855]
### EDM Env:
runtime = `cpython  3.6.9+2   osx_x86_64  darwin`
```
appdirs==1.4.3
distribute-remove==1.0.0
icu4c==50.2
libjpeg==7.0
libpng==1.6.36
packaging==16.8
pyface==7.0.0
Pygments==2.2.0
pyparsing==2.2.0
PyQt5==5.14.2
PyQt5-sip==12.7.2
Qt==5.12.6
six==1.11.0
traits==6.0.0
traitsui==7.0.0
```

### Description:
When using a `ListStrEditor` to display items in a list, in combination with a `Button` that appends new items to the list, the UI does not refresh correctly if the button is pressed whilst an item is selected. The UI displays the expected behavior only if an item is not selected.

![liststreditor_bug](https://user-images.githubusercontent.com/50372949/83284913-4f5fb600-a1d5-11ea-97d4-1869808119e8.gif)

The new items are appended correctly to the list object and they can be selected, so it seems as if the table is not redrawn correctly following the update. 

It is worth noting that the same behavior can also be observed when using a `TabularEditor` that displays a list of `HasTraits` classes as table rows, even when assigning the `update` or `refresh` traits. Therefore the inclusion of an `update` event in the `ListStrEditor` as suggested in #511 may not resolve this issue.

It is possible that this could be a Qt issue (maybe related to #791), but I have tried to test using a Wx backend (`wxPython==4.1.0`, just by putting `import wx` in the imports) and I observe the same behavior.

### Code stub:

```python
from traits.api import HasTraits, List, Button
from traitsui.api import View, UItem, Label, ListStrEditor


class MyListView(HasTraits):

    add = Button()

    rows = List()

    def default_traits_view(self):

        list_str_editor = ListStrEditor()

        return View(
            Label('List'),
            UItem('add'),
            UItem("rows", editor=list_str_editor),
            resizable=True,
        )

    def _add_changed(self):
        self.rows.append(0)

if __name__=='__main__':
    rows = [1, 2]
    my_list = MyListView(rows=rows)
    my_list.configure_traits()
```

**Comment by flongford** [comment]
Note: this was observed on MacOS 10.15.4

**Comment by corranwebster** [comment]
I suspect that this is related to https://github.com/enthought/traits/issues/537 - it was causing issues with regular list editor updates.

A possible fix, given that the above is not likely to be fixed, is to add an `update` trait to the factory that holds the name of an event trait that is fired when the contents change. Implementation would be essentially the same as the `TabularEditor`'s version.  This would also allow use of the `ListStrEditor` with non-traits lists via an adaptor.

**Comment by kitchoi** [comment]
We believe this is fixed by #875.
@flongford could you please confirm if we could close this issue?
(Note the fix will be included in the next bug release.)

**Comment by flongford** [comment]
Hi @kitchoi - many thanks for your help.

I can confirm that this issue has been resolved using a Qt4 backend:

```
pyqt  4.12.1-1
qt    4.8.7-12
sip   4.19.2-2 
```

But I still experience the same reported behavior when using Qt5 packages:

```
icu4c      50.2-2
libjpeg    7.0-5
libpng     1.6.36-3
libxml2    2.9.7-1
libxslt    1.1.30-1
pyqt5      5.14.2-3 
pyqt5_sip  12.7.2-1 
```

Is this to be expected?

**Comment by kitchoi** [comment]
@flongford Thank you for checking! 
That's weird because I still couldn't reproduce it, and I think both of us are testing this on Mac OSX.
Do you mind showing the Qt version as well please? The Qt version does not have to be identical to the `pyqt5` version.
Mine is `qt 5.12.6-5`

**Comment by kitchoi** [comment]
Ah! I think I need to click on an item in the list first before clicking the button. Yep I can reproduce. Sorry about that.

Looks like this is similar to what we have seen all over the place with Mac OSX and Qt5, where events following clicking a button are not processed.  See #913

**Comment by flongford** [comment]
> Ah! I think I need to click on an item in the list first before clicking the button. Yep I can reproduce. Sorry about that.
> 
> Looks like this is similar to what we have seen all over the place with Mac OSX and Qt5, where events following clicking a button are not processed immediately. See #913

No worries, yes my Qt version was also ` 5.12.6-5`, sorry for missing it out.

Thanks for the issue reference - yes, I believe it's related to the same problem since we used the `GUI.process_events` workaround to resolve this behavior in our production code. Will keep an eye on how it progresses
